export interface Category {
  value: string;
  label: string;
}

export const options: Category[] = [
  {value: "ACTING" , label: "Acting"},
  {value: "AGED_CARE" , label: "AgedCare"},
  {value: "AGRIBUSINESS_MANAGEMENT" , label: "Agribusiness Management"},
  {value: "AI" , label: "Ai"},
  {value: "ANIMATION_3D" , label: "Animation 3D"},
  {value: "AUTOMOTIVE" , label: "Automotive"},
  {value: "BAKING" , label: "Baking"},
  {value: "BANKING_MANAGEMENT" , label: "Banking Management"},
  {value: "BEAUTY" , label: "Beauty"},
  {value: "BLOCKCHAIN_TECH" , label: "Blockchain Tech"},
  {value: "BLOG" , label: "Blog"},
  {value: "BUSINESS_ANALYSIS" , label: "Business Analysis"},
  {value: "BUSINESS_MANAGEMENT" , label: "Business Management"},
  {value: "CARPENTRY" , label: "Carpentry"},
  {value: "CLOUD_COMPUTING" , label: "Cloud_Computing"},
  {value: "COMMERCIAL_COOKING" , label: "Commercial Cooking"},
  {value: "COMPUTER_NETWORKING" , label: "Computer Networking"},
  {value: "CONSTRUCTION" , label: "Construction"},
  {value: "DATA_MANAGEMENT" , label: "Data Management"},
  {value: "DENTAL" , label: "Dental"},
  {value: "DESIGN", label: "Design"},
  {value: "DIGITAL_MEDIA" , label: "Digital Media"},
  {value: "EDUCATION" , label: "Education"},
  {value: "EVENTS" , label: "Events"},
  {value: "FASHION_DESIGN" , label: "Fashion Design"},
  {value: "FILM_MEDIA" , label: "Film Media"},
  {value: "FITNESS" , label: "Fitness"},
  {value: "GAME_PROGRAMMING" , label: "Game Programming"},
  {value: "GRAPHIC_DESIGN" , label: "Graphic Design"},
  {value: "HARIDRESSING" , label: "Haridressing"},
  {value: "HOPITALITY_MANAGEMENT" , label: "Hopitality Management"},
  {value: "HORTICULTURE" , label: "Horticulture"},
  {value: "HUMAN_RESOURCES" , label: "Human Resources"},
  {value: "INTERIOR_DESIGN" , label: "Interior Design"},
  {value: "INTERNATIONAL_BUSINESS" , label: "International Business"},
  {value: "INTL_HOTEL_MANAGEMENT" , label: "Intl Hotel Management"},
  {value: "LANDSCAPE" , label: "Landscape"},
  {value: "LEADERSHIP_MANAGEMENT" , label: "Leadership Management"},
  {value: "MACHINE_LEARNING" , label: "Machine Learning"},
  {value: "MASSAGE" , label: "Massage"},
  {value: "MEDICINE" , label: "Medicine"},
  {value: "MENTAL_HEALTH" , label: "Mental Health"},
  {value: "MUSIC_AUDIO" , label: "Music Audio"},
  {value: "NURSING" , label: "Nursing"},
  {value: "NUTRITION" , label: "Nutrition"},
  {value: "PROJECT_MANAGEMENT" , label: "Project Management"},
  {value: "PUBLIC_HEALTH" , label: "Public Health"},
  {value: "SOCIALMEDIA_MARKETING" , label: "Socialmedia Marketing"},
  {value: "SOFTWARE_DEVELOPMENT" , label: "Software Development"},
  {value: "SPORT" , label: "Sport"},
  {value: "SUPPLYCHAIN_MANAGEMENT" , label: "Supplychain Management"},
  {value: "TELECOMMUNICATION" , label: "Telecommunication"},
  {value: "TRAVEL_TOURISM" , label: "Travel & Tourism"},
  {value: "VETENARY" , label: "Vetenary"},
  {value: "WEB_DEVELOPMENT" , label: "Web Development"},
  {value: "YOGA" , label: "Yoga"},
  {value: "map" , label: "map"},
];